export { AstronautСardOne } from './AstronautsCardOne'
export { AstronautСardTwo } from './AstronautsCardTwo'
export { AstronautСardThree } from './AstronautsCardThree'
export { AstronautСardFour } from './AstronautsCardFour'
export { AstronautСardFive } from './AstronautsCardFive'